sudo: true
language: node_js
node_js:
  - 16 # use nodejs v12 LTS
cache: 
  - npm 
  - pandoc
  - hexo-cli
  - hexo-renderer-pandoc
install:
  - wget https://github.com/jgm/pandoc/releases/download/2.7/pandoc-2.7-1-amd64.deb
  - sudo dpkg -i ./pandoc-2.7-1-amd64.deb
  - npm install -g hexo-cli
  - npm uninstall hexo-renderer-marked --save
  - npm install hexo-renderer-pandoc --save
branches:
  only:
    - main # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public